server:
  port: 8080

spring:
  datasource:
    username: root
    password: 107754
    url: jdbc:mysql://www.lvning.club:3306/hhsturim?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update



