server:
  port: 8091

#  servlet:
#    session:
#      timeout: 1m

#上传图片存放路径
hhsturim:
  uploadfilepath: F:/imgs/

spring:
  datasource:
    username: root
    password: 107754
    url: jdbc:mysql://www.lvning.club:3306/hhsturim?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall,slf4j
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
#    open-in-view: false

shiro:
  loginUrl: /login.html


